1944_Campaign_1_Chapter_001.smf: texture.png heightmap.png typemap.png metalmap.png minimap.png features.txt
	springMapConvNG -t texture.png -h heightmap.png -z typemap.png -m metalmap.png -maxh 40.0 -minh -10.0 -th 0.8 -ct 4 -features features.txt -minimap minimap.png -o "1944_Campaign_1_Chapter_001"
